# Generated by Django 3.2.5 on 2021-09-09 02:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SessionYearModel',
            new_name='SessionYear',
        ),
    ]
