# Generated by Django 3.2.5 on 2021-09-03 16:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_auto_20210903_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='courses',
            name='update_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
