# Generated by Django 3.2.5 on 2021-09-03 18:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_auto_20210903_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='admin',
            name='update_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
