# Criado em 06.10.2022
# https://github.com/marketplace/actions/publish-to-github-wiki



name: Documentation

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      # Additional steps to generate documentation in "Documentation" directory
      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "wiki"
        env:
          #  GH_PERSONAL_ACCESS_TOKEN
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
          